[2024-11-11 04:26:14,046][src.utils.utils][INFO] - [rank: 0] Enforcing tags! <cfg.extras.enforce_tags=True>
[2024-11-11 04:26:14,051][src.utils.utils][INFO] - [rank: 0] Printing config tree with Rich! <cfg.extras.print_config=True>
[2024-11-11 04:26:14,052][src.utils.rich_utils][WARNING] - [rank: 0] Field 'logger' not found in config. Skipping 'logger' config printing...
[2024-11-11 04:26:14,093][__main__][INFO] - [rank: 0] Instantiating datamodule <src.data.kinetics_datamodule.KineticsDataModule>
[2024-11-11 04:26:15,179][__main__][INFO] - [rank: 0] Instantiating model <src.models.vit_mae.VITModule>
[2024-11-11 04:26:21,507][__main__][INFO] - [rank: 0] Instantiating callbacks...
[2024-11-11 04:26:21,508][src.utils.instantiators][INFO] - [rank: 0] Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2024-11-11 04:26:21,512][src.utils.instantiators][INFO] - [rank: 0] Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2024-11-11 04:26:21,513][src.utils.instantiators][INFO] - [rank: 0] Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2024-11-11 04:26:21,513][__main__][INFO] - [rank: 0] Instantiating loggers...
[2024-11-11 04:26:21,514][src.utils.instantiators][WARNING] - [rank: 0] No logger configs found! Skipping...
[2024-11-11 04:26:21,514][__main__][INFO] - [rank: 0] Instantiating trainer <pytorch_lightning.trainer.Trainer>
[2024-11-11 04:26:21,529][__main__][INFO] - [rank: 0] Starting testing!
[2024-11-11 04:26:21,529][__main__][WARNING] - [rank: 0] Best ckpt not found! Using current weights for testing...
[2024-11-11 04:26:39,229][src.utils.utils][ERROR] - [rank: 0] 
Traceback (most recent call last):
  File "/home/rchoudhu/research/compressvit/pregrouping-release-debug/src/utils/utils.py", line 72, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/rchoudhu/research/compressvit/pregrouping-release-debug/src/train.py", line 99, in train
    trainer.test(model=model, datamodule=datamodule, ckpt_path=ckpt_path)
  File "/usr/local/anaconda3/envs/rlt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 753, in test
    return call._call_and_handle_interrupt(
  File "/usr/local/anaconda3/envs/rlt/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/usr/local/anaconda3/envs/rlt/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/usr/local/anaconda3/envs/rlt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 793, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/anaconda3/envs/rlt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 948, in _run
    call._call_setup_hook(self)  # allow user to set up LightningModule in accelerator environment
  File "/usr/local/anaconda3/envs/rlt/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 92, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "/usr/local/anaconda3/envs/rlt/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 179, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/home/rchoudhu/research/compressvit/pregrouping-release-debug/src/data/kinetics_datamodule.py", line 83, in setup
    raise RuntimeError(
RuntimeError: Batch size (14) is not divisible by the number of devices (4).
[2024-11-11 04:26:39,231][src.utils.utils][INFO] - [rank: 0] Output dir: /home/rchoudhu/research/compressvit/pregrouping-release-debug/logs/vitl_test/runs/2024-11-11_04-26-13
